<a href="https://colab.research.google.com/github/ChrisRamirez02/Phase3Ramirez/blob/main/Phase3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Random Forest- Alexis (Present)

In [49]:
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

df = pd.read_csv("/content/NegativeResultOnly(Sheet 3 All Data).csv")

print("Dataset Shape:", df.shape)
print("Column Names:", df.columns.tolist())
print("\nFirst 5 rows:")
print(df.head())

Dataset Shape: (12091, 29)
Column Names: ['Case_Id', 'Age', 'Min-Max Scaling Age', 'Age_Group', 'Age_Group(0,1,2)', 'Min-Max Scaling Age Group', 'Sex', 'Sex(0,1)', 'Province', 'Municipality', 'Region', 'Island', 'Region (0,1,2)', 'Min-Max Region', 'Region_NCR', 'Pregnant', 'Pregnant(0,1,2)', 'Min-Max Pregnant', 'Status', 'Status Severity', 'Min-Max Status Severity', 'Health_Status', 'Health_Status(0,1,2,3,4,5)', 'Min-Max Health Status', 'High_Risk', 'Is_Symptomatic', 'Mortality Risk', 'Min-Max Mortality Risk', 'Final Status']

First 5 rows:
   Case_Id  Age  Min-Max Scaling Age Age_Group  Age_Group(0,1,2)  \
0  C404174   38                 0.38     Adult                 1
1  C462688   44                 0.44     Adult                 1
2  C387710   60                 0.60    Senior                 2
3  C377460   48                 0.48     Adult                 1
4  C498051   62                 0.62    Senior                 2

   Min-Max Scaling Age Group     Sex  Sex(0,1)             Province  \
0                        0.5  Female         1      Negros Oriental
1                        0.5    Male         0      Negros Oriental
2                        1.0  Female         1                Bohol
3                        0.5    Male         0  Metropolitan Manila
4                        1.0    Male         0                Rizal

     Municipality  ... Status Severity Min-Max Status Severity  Health_Status  \
0  Dumaguete City  ...               1                    0.25      Recovered
1  Dumaguete City  ...               4                    1.00           Died
2         Panglao  ...               1                    0.25      Recovered
3          Taguig  ...               1                    0.25      Recovered
4          Cainta  ...               4                    1.00           Died

   Health_Status(0,1,2,3,4,5)  Min-Max Health Status High_Risk  \
0                           0                    0.0         0
1                           5                    1.0         0
2                           0                    0.0         1
3                           0                    0.0         0
4                           5                    1.0         1

   Is_Symptomatic  Mortality Risk Min-Max Mortality Risk  Final Status
0               1             0.0                   0.00             0
1               1             2.2                   0.44             1
2               1             0.0                   0.00             0
3               1             0.0                   0.00             0
4               1             3.1                   0.62             1

[5 rows x 29 columns]

In [50]:
X = df.drop('Final Status', axis=1)
y = df['Final Status']

print("\nTarget variable unique values:")
print(y.unique())

rf = RandomForestClassifier(random_state=42)
print("Model Selected: Random Forest Classifier")

Target variable unique values:
[0 1]
Model Selected: Random Forest Classifier

In [51]:
# Split the dataset into training (80%) and testing (20%)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print("Training Set Shape:", X_train.shape)
print("Testing Set Shape:", X_test.shape)

Training Set Shape: (9672, 28)
Testing Set Shape: (2419, 28)

In [52]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object', 'category']).columns

numeric_transformer = SimpleImputer(strategy='median')

categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ]
)

model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', RandomForestClassifier(random_state=42))
])

model.fit(X_train, y_train)

print("✅ Model training complete! Random Forest classifier is ready.")
y_pred = model.predict(X_test)

✅ Model training complete! Random Forest classifier is ready.

In [53]:
y_pred = model.predict(X_test)

print("Sample Predictions:")
print(y_pred[:10])

Sample Predictions:
[0 0 0 0 0 0 0 0 0 0]

In [54]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("\nModel Evaluation Results:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))

Model Evaluation Results:
Accuracy: 1.0

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2261
           1       1.00      1.00      1.00       158

    accuracy                           1.00      2419
   macro avg       1.00      1.00      1.00      2419
weighted avg       1.00      1.00      1.00      2419


Confusion Matrix:
 [[2261    0]
 [   0  158]]

In [55]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'classifier__n_estimators': [100, 200],
    'classifier__max_depth': [None, 5, 10],
    'classifier__min_samples_split': [2, 5],
    'classifier__min_samples_leaf': [1, 2]
}

grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    cv=3,
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

print("\nBest Parameters:", grid_search.best_params_)
best_model = grid_search.best_estimator_

Fitting 3 folds for each of 24 candidates, totalling 72 fits

Best Parameters: {'classifier__max_depth': None, 'classifier__min_samples_leaf': 1, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 100}

In [56]:
y_pred_best = best_model.predict(X_test)

# Evaluate the tuned model’s performance
print("\nTuned Model Accuracy:", accuracy_score(y_test, y_pred_best))
print("\nTuned Model Classification Report:\n", classification_report(y_test, y_pred_best))
print("\nTuned Model Confusion Matrix:\n", confusion_matrix(y_test, y_pred_best))

Tuned Model Accuracy: 1.0

Tuned Model Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      2261
           1       1.00      1.00      1.00       158

    accuracy                           1.00      2419
   macro avg       1.00      1.00      1.00      2419
weighted avg       1.00      1.00      1.00      2419


Tuned Model Confusion Matrix:
 [[2261    0]
 [   0  158]]

**DECISION TREES - Bernard**

In [57]:
# =====================================================
# 🌳 DECISION TREE CLASSIFICATION
# =====================================================

# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# =====================================================
# Load Dataset
# =====================================================
# Define the raw GitHub URL as a string
url = 'https://github.com/ChrisRamirez02/Phase3Ramirez'

# Use pandas to read the CSV directly into a DataFrame
df = pd.read_csv(url)

# Display the first few rows of the DataFrame
print(df.head())

# =====================================================
# Clean Dataset Preview (Formatted)
# =====================================================

print("\n📊 Dataset Preview:")
display(data.head())

print("\n🧾 Column Names:")
display(pd.DataFrame(data.columns, columns=["Columns"]))

print("\n🔎 Data Types:")
display(data.dtypes.to_frame("Data Type"))

# =====================================================
# Handle NaN values in the target variable
# =====================================================
data.dropna(subset=['Final Status'], inplace=True)

# =====================================================
# 4️⃣ Define Features (X) and Target (y)
# =====================================================

X = data.drop(columns=["Final Status", "Unnamed: 19", "Unnamed: 20", "Unnamed: 21", "1036484"])
y = data["Final Status"]

# =====================================================
# 5️⃣ One-Hot Encode Categorical Columns
# =====================================================

categorical_cols = X.select_dtypes(include=["object"]).columns
X = pd.get_dummies(X, columns=categorical_cols, drop_first=True)

print(f"\nTotal Features after encoding: {X.shape[1]}")

# =====================================================
# 6️⃣ Train-Test Split
# =====================================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

# =====================================================
# 7️⃣ Create Decision Tree Model
# =====================================================

model = DecisionTreeClassifier(
    criterion="gini",   # or "entropy"
    max_depth=5,
    random_state=42
)

# =====================================================
# 8️⃣ Train Model
# =====================================================

model.fit(X_train, y_train)

# =====================================================
# 9️⃣ Predictions
# =====================================================

y_pred = model.predict(X_test)

# =====================================================
# 🔟 Formatted Performance Output
# =====================================================

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("\n" + "="*55)
print("📊 DECISION TREE MODEL PERFORMANCE")
print("="*55)

# Accuracy
print(f"\n✅ Accuracy: {accuracy*100:.2f}%")

# Classification Report
print("\n📄 Classification Report")
print("-"*55)
print(classification_report(y_test, y_pred, digits=4))

# Confusion Matrix
print("\n🧩 Confusion Matrix")
print("-"*55)
print("             Predicted")
print("             0     1")
print(f"Actual 0     {cm[0][0]}     {cm[0][1]}")
print(f"Actual 1     {cm[1][0]}     {cm[1][1]}")

print("="*55)

📊 Dataset Preview:

,ï»¿Case_Id,Age,Min-Max Scaling Age,Age_Group,"Age_Group(0,1,2)",Min-Max Scaling Age Group,Sex,"Sex(0,1)",Province,Municipality,...,Status Severity,Min-Max Status Severity,Health_Status,"Health_Status(0,1,2,3,4,5)",Min-Max Health Status,High_Risk,Is_Symptomatic,Mortality Risk,Min-Max Mortality Risk,Final Status
0,C404174,38,0.38,Adult,1,0.5,Female,1,Negros Oriental,Dumaguete City,...,1,0.25,Recovered,0,0.0,0,1,0.0,0.00,0
1,C462688,44,0.44,Adult,1,0.5,Male,0,Negros Oriental,Dumaguete City,...,4,1.00,Died,5,1.0,0,1,2.2,0.44,1
2,C387710,60,0.60,Senior,2,1.0,Female,1,Bohol,Panglao,...,1,0.25,Recovered,0,0.0,1,1,0.0,0.00,0
3,C377460,48,0.48,Adult,1,0.5,Male,0,Metropolitan Manila,Taguig,...,1,0.25,Recovered,0,0.0,0,1,0.0,0.00,0
4,C498051,62,0.62,Senior,2,1.0,Male,0,Rizal,Cainta,...,4,1.00,Died,5,1.0,1,1,3.1,0.62,1

🧾 Column Names:

                       Columns
0                   ï»¿Case_Id
1                          Age
2          Min-Max Scaling Age
3                    Age_Group
4             Age_Group(0,1,2)
5    Min-Max Scaling Age Group
6                          Sex
7                     Sex(0,1)
8                     Province
9                 Municipality
10                      Region
11                      Island
12              Region (0,1,2)
13              Min-Max Region
14                  Region_NCR
15                    Pregnant
16             Pregnant(0,1,2)
17            Min-Max Pregnant
18                      Status
19             Status Severity
20     Min-Max Status Severity
21               Health_Status
22  Health_Status(0,1,2,3,4,5)
23       Min-Max Health Status
24                   High_Risk
25              Is_Symptomatic
26              Mortality Risk
27      Min-Max Mortality Risk
28                Final Status

🔎 Data Types:

                           Data Type
ï»¿Case_Id                    object
Age                            int64
Min-Max Scaling Age          float64
Age_Group                     object
Age_Group(0,1,2)               int64
Min-Max Scaling Age Group    float64
Sex                           object
Sex(0,1)                       int64
Province                      object
Municipality                  object
Region                        object
Island                        object
Region (0,1,2)                 int64
Min-Max Region               float64
Region_NCR                     int64
Pregnant                      object
Pregnant(0,1,2)                int64
Min-Max Pregnant             float64
Status                        object
Status Severity                int64
Min-Max Status Severity      float64
Health_Status                 object
Health_Status(0,1,2,3,4,5)     int64
Min-Max Health Status        float64
High_Risk                      int64
Is_Symptomatic                 int64
Mortality Risk               float64
Min-Max Mortality Risk       float64
Final Status                   int64

KeyError: "['Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21', '1036484'] not found in axis"

In [ ]:
# =====================================================
# 1️⃣1️⃣ Decision Tree Visualization
# =====================================================

plt.figure(figsize=(20,10))

plot_tree(
    model,
    feature_names=X.columns,
    class_names=["0", "1"],
    filled=True,
    rounded=True,
    fontsize=9
)

plt.title("Decision Tree Visualization")
plt.show()

# =====================================================
# 1️⃣2️⃣ Save Tree as Image (Optional)
# =====================================================

plt.figure(figsize=(20,10))

plot_tree(
    model,
    feature_names=X.columns,
    class_names=["0", "1"]
)

## **Chris Logistic Regression**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.metrics import roc_curve, auc
import joblib

# Define Features and Target
features = ['Age', 'Sex(0,1)', 'Region (0,1,2)', 'Pregnant(0,1,2)', 'High_Risk', 'Is_Symptomatic']
target = 'Final Status'

X = df[features]
y = df[target]

# --- STEP 2: MODEL TRAINING ---
# Split: 80% Train, 20% Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Scale: Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train: Logistic Regression
model = LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)
model.fit(X_train_scaled, y_train)

# --- STEP 3: EVALUATION ---
y_pred = model.predict(X_test_scaled)

# Calculate Metrics
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print(f"Model Accuracy: {accuracy:.2f}")
print("\nClassification Report:\n", report)

# --- STEP 4: VISUALIZATION ---
plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Recovered (0)', 'Died (1)'],
            yticklabels=['Recovered (0)', 'Died (1)'])
plt.title('Confusion Matrix: Logistic Regression')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.tight_layout()
plt.show()
print("\n" * 4)

# --- 4.2: FEATURE IMPORTANCE (Coefficients) ---
# Explanation: Shows which variables increase or decrease the risk of death.
plt.figure(figsize=(10, 6))
coeffs = pd.DataFrame({
    'Feature': features,
    'Coefficient': model.coef_[0]
})
# Sort by value for better readability
coeffs = coeffs.sort_values(by='Coefficient', ascending=False)

# --- FIX APPLIED HERE ---
# Added hue='Feature' and legend=False to fix the FutureWarning
sns.barplot(x='Coefficient', y='Feature', hue='Feature', data=coeffs, palette='viridis', legend=False)

plt.title('Feature Importance (Logistic Regression Coefficients)')
plt.xlabel('Coefficient Value (Positive = Increased Risk, Negative = Decreased Risk)')
plt.axvline(x=0, color='black', linestyle='--')
plt.tight_layout()
plt.show()
print("\n" * 4)

# --- 4.3: ROC CURVE ---
# Get predicted probabilities
y_prob = model.predict_proba(X_test_scaled)[:, 1]
fpr, tpr, thresholds = roc_curve(y_test, y_prob)
roc_auc = auc(fpr, tpr)

plt.figure(figsize=(8, 6))
plt.plot(fpr, tpr, color='darkorange', lw=2, label=f'ROC curve (AUC = {roc_auc:.2f})')
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate (False Alarms)')
plt.ylabel('True Positive Rate (Sensitivity)')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.tight_layout()
plt.show()
print("\n" * 4)

# --- 4.4: PREDICTION PROBABILITY DISTRIBUTION ---
plt.figure(figsize=(8, 6))
sns.histplot(y_prob[y_test == 0], color='blue', label='Actual: Recovered', kde=True, element="step", alpha=0.3)
sns.histplot(y_prob[y_test == 1], color='red', label='Actual: Died', kde=True, element="step", alpha=0.3)
plt.title('Distribution of Predicted Probabilities')
plt.xlabel('Predicted Probability of Death (0.0 to 1.0)')
plt.ylabel('Count of Patients')
plt.legend()
plt.tight_layout()
plt.show()

# RandomForest Classifier (Kyla)

In [ ]:
# Define features (X) and target (y)
# 'Final Status' is chosen as the target variable.
# We will drop 'Case_Id' as it's an identifier and the original string categorical columns
# (like 'Age_Group', 'Sex', etc.) for which numerical encodings already exist.
# Additionally, we will drop features identified as causing data leakage.

y = df['Final Status'] # Target variable

# Features: Drop the target column, Case_Id, original string categorical columns,
# and features identified as leaking information about 'Final Status'.
X = df.drop(columns=[
    'Final Status',
    'Case_Id',
    'Age_Group',
    'Sex',
    'Province',
    'Municipality',
    'Region',
    'Island',
    'Pregnant',
    'Status',
    'Status Severity',
    'Health_Status',
    'Min-Max Health Status', # Leaking feature
    'Health_Status(0,1,2,3,4,5)', # Leaking feature
    'Min-Max Status Severity', # Leaking feature
    'Min-Max Mortality Risk', # Leaking feature
    'Mortality Risk' # Leaking feature
])

# Train-Test Split (70% Train, 30% Test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"Training set shape: {X_train.shape}, {y_train.shape}")
print(f"Testing set shape: {X_test.shape}, {y_test.shape}")

# Model: Random Forest Classifier
model = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluate the Model
# Using classification metrics: Accuracy and Classification Report (Precision, Recall, F1)
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print(f"Random Forest Classifier Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(report)

# Feature Importance
# Get feature names from the trained X_train DataFrame
feature_names = X_train.columns.tolist()
importance = pd.DataFrame({
    'Feature': feature_names,
    'Importance': model.feature_importances_
}).sort_values(by='Importance', ascending=False)

print("\nFeature Importance:")
print(importance)

In [ ]:
print("Data types of top important features:")
print(df[['Min-Max Health Status', 'Health_Status(0,1,2,3,4,5)', 'Min-Max Status Severity', 'Min-Max Mortality Risk', 'Mortality Risk', 'Final Status']].dtypes)

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

# Set up the plotting style
sns.set_style("whitegrid")

# List of top features to visualize against 'Final Status'
top_features = [
    'Min-Max Health Status',
    'Health_Status(0,1,2,3,4,5)',
    'Min-Max Status Severity',
    'Min-Max Mortality Risk',
    'Mortality Risk'
]

plt.figure(figsize=(15, 10))
for i, feature in enumerate(top_features):
    plt.subplot(3, 2, i + 1) # Arrange plots in a 3x2 grid

    # Check if the feature is suitable for a countplot (e.g., has few unique values)
    if df[feature].nunique() < 20:
        sns.countplot(data=df, x=feature, hue='Final Status', palette='viridis')
    else:
        # For features with many unique values, a boxplot or violin plot might be more suitable
        sns.boxplot(data=df, x='Final Status', y=feature, palette='viridis')

    plt.title(f'Distribution of {feature} by Final Status')
    plt.tight_layout()

plt.show()